### ISSUE TITLE
Create a NationalGrid Preprocessor

### ISSUE THREAD

**Issue by RogerTangos** [RogerTangos/LostLeaks#6]
Similar to what @ainzero did with the Eversource Preprocessor. Keep in mind that NationalGrid assigns its leaks and repairs unique keys (unlike eversource) and that it sometimes uses [shortcodes for cities and towns](https://github.com/RogerTangos/NatGas/blob/master/sanitization/parsing.py#L46).

**Comment by ainzero** [comment]
I'll start work on this today.

**Comment by ainzero** [comment]
I submitted a pull request regarding this today.

**Comment by RogerTangos** [comment]
Closed by #7
